var e=[12,13,13,13,13,13,13,13],l=[.8,.6,.5,.5,.4],t=[1,1,1,1.5,2,3,5,6,6,4,3,2],u=["#78f378","#0000c3","red"],v,w,x,y,z={},B=-1,C=-1,D="Move into a <span class='grouplink' onmouseover='grHl(${tid})' onmouseout='grUnHl(${tid})'>new relation</span> <tt>public_transport=stop_area</tt>.;Move into relation <a onmouseover='grHl(${tid})' onmouseout='grUnHl(${tid})' href=\"//www.openstreetmap.org/relation/${toid}\" target=\"_blank\">${toid}</a>.;Move from relation <a onmouseover='grHl(${oid})' onmouseout='grUnHl(${oid})' href=\"//www.openstreetmap.org/relation/${ooid}\" target=\"_blank\">${ooid}</a> into a <span class='grouplink' onmouseover='grHl(${tid})' onmouseout='grUnHl(${tid})'>new relation</span> <tt>public_transport=stop_area</tt>.;Move from relation <a onmouseover='grHl(${oid})' onmouseout='grUnHl(${oid})' href=\"//www.openstreetmap.org/relation/${ooid}\" target=\"_blank\">${ooid}</a> into relation <a onmouseover='grHl(${tid})' onmouseout='grUnHl(${tid})' href=\"//www.openstreetmap.org/relation/${toid}\" target=\"_blank\">${toid}</a>.;Move out of relation <a onmouseover='grHl(${oid})' onmouseout='grUnHl(${oid})' href=\"//www.openstreetmap.org/relation/${ooid}\" target=\"_blank\">${ooid}</a>;Fix attribute <tt>${attr}</tt>.;Consider adding a <tt><a target='_blank' href='https://wiki.openstreetmap.org/wiki/Key:name'>name</a></tt> attribute.;Attribute <tt>${attr}</tt> seems to be a track number. Use <tt>ref</tt> for this and set <tt>${attr}</tt> to the station name.".split(";");
function E(a){return"#"==a[0]?document.getElementById(a.substr(1)):"."==a[0]?document.getElementsByClassName(a.substr(1)):document.getElementsByTagName(a)}function F(a){return document.createElement(a)}function G(a,c){-1==a.className.split(" ").indexOf(c)&&(a.className+=" "+c);a.className=a.className.trim()}function H(a){return a.e?u[2]:a.O?u[1]:u[0]}function I(a,c){for(p in c)a=a.replace(new RegExp("\\${"+p+"}","g"),c[p]);return a}
function J(a,c,b){z[a]&&z[a].abort();z[a]=new XMLHttpRequest;z[a].onreadystatechange=function(){4==this.readyState&&200==this.status&&this==z[a]&&b(JSON.parse(this.responseText))};z[a].open("GET",c,1);z[a].send()}
function K(a){var c=M.b();return 1==a.u.length?15<c?L.ka(a.u[0],{color:"#000",fillColor:H(a),J:t[23-c],B:1,weight:17<c?1.5:1,id:a.j}):L.$([a.u[0],a.u[0]],{color:H(a),fillColor:H(a),weight:e[15-c],opacity:l[15-c],id:a.j}):L.Z(a.u,{color:15<c?"#000":H(a),fillColor:H(a),P:0,B:.75,weight:17<c?1.5:1,id:a.j})}function N(a){var c=M.b(),b=a.e?"red":a.O?"#0000c3":"#85f385",b={color:b,fillColor:b,P:.4,B:.2,id:a.j};16>c&&(b.weight=11,b.opacity=.5,b.B=.5);return L.Z(a.u,b)}
function O(a){M.b();return L.$(a.ga,{id:a.j,color:"#0000c3",P:.1,weight:4,opacity:.5})}
function P(a){C=a.id;Q(a.id);var c={},b=Math.abs(a.c),h=0>a.c?"Way":"Node",n=F("div");n.setAttribute("id","nav");var f=F("div");f.setAttribute("id","sugg");n.innerHTML=h+" <a target='_blank' href='//www.openstreetmap.org/"+h.toLowerCase()+"/"+b+"'>"+b+"</a>";a.f.name&&(n.innerHTML+=' (<b>"'+a.f.name+'"</b>)');n.innerHTML+="<a class='ebut' target='_blank' href='//www.openstreetmap.org/"+h.toLowerCase()+"="+b+"'>&#9998;</a>";b=F("table");b.setAttribute("id","attr-tbl");n.appendChild(b);n.appendChild(f);
h=F("tbody");b.appendChild(h);for(var d in a.f){var q=F("tr"),b=F("td"),m=F("td");G(m,"err-wrap");h.appendChild(q);q.appendChild(b);q.appendChild(m);b.innerHTML='<a href="https://wiki.openstreetmap.org/wiki/Key:'+d+'" target="_blank"><tt>'+d+"</tt></a>";for(b=0;b<a.f[d].length;b++)m.innerHTML+="<span class='attrval'>"+a.f[d][b]+"</span><br>";c[d]=q}for(b=0;b<a.w.length;b++)d=a.w[b],q=c[d.s[0]],G(q,"err-"+Math.round(10*d.W)),m=F("div"),d.h?m.innerHTML=1<d.a?"Does not match <tt>"+d.g[0]+"</tt> in relation <a onmouseover='grHl( "+
d.h+")' onmouseout='grUnHl( "+d.h+')\' target="_blank" href="//www.openstreetmap.org/relation/'+Math.abs(d.a)+'">'+Math.abs(d.a)+"</a>":"Does not match <tt>"+d.g[0]+"</tt> in relation <span onmouseover='grHl( "+d.h+")' onmouseout='grUnHl( "+d.h+")'>"+Math.abs(d.a)+"</span>":d.a!=a.c?(h=0>d.a?"way":"node",m.innerHTML="Does not match <tt>"+d.g[0]+"</tt> in "+h+" <a onmouseover='stHl( "+d.I+")' onmouseout='stUnHl( "+d.I+')\' target="_blank" href="//www.openstreetmap.org/'+h+"/"+Math.abs(d.a)+'">'+Math.abs(d.a)+
"</a>"):m.innerHTML="Does not match <tt>"+d.g[0]+"</tt> = '"+d.g[1]+"'",G(m,"attr-err-info"),q.childNodes[1].appendChild(m);c=F("ul");a.m.length&&(b=F("span"),G(b,"sugtit"),b.innerHTML="Suggestions",f.appendChild(b));f.appendChild(c);for(b=0;b<a.m.length;b++)f=a.m[b],d=F("li"),d.innerHTML=I(D[f.type-1],{attr:f.s,tid:f.va,ooid:f.pa,toid:f.wa,oid:f.na}),c.appendChild(d);L.aa({opacity:.8}).ca(a).ba(n).Y(M).l("remove",function(){C=-1;R(a.id)})}function S(a){J("s","/stat?id="+a,function(a){P(a)})}
function T(a,c){B=a.id;var b={};U(a.id);var h=F("div");h.setAttribute("id","nav");var n=F("div");n.setAttribute("id","group-stations-new");n.innerHTML="<span class='newmemberstit'>New Members</span>";var f=F("div");f.setAttribute("id","group-stations-old");f.innerHTML="<span class='oldmemberstit'>Existing Members</span>";1==a.c?h.innerHTML="<span class='grouplink'>New relation</span> <tt>public_transport=stop_area</tt>":(h.innerHTML="OSM relation <a target='_blank' href='https://www.openstreetmap.org/relation/"+
a.c+"'>"+a.c+"</a>",a.f.name&&(h.innerHTML+=' (<b>"'+a.f.name+'"</b>)'),h.innerHTML+="<a class='ebut' target='_blank' href='https://www.openstreetmap.org/edit?relation="+a.c+"'>&#9998;</a>");var d=F("table");d.setAttribute("id","attr-tbl");h.appendChild(d);var q=F("tbody");d.appendChild(q);d=F("div");d.setAttribute("id","sugg");for(var m in a.f){var r=F("tr"),k=F("td"),g=F("td");G(g,"err-wrap");q.appendChild(r);r.appendChild(k);r.appendChild(g);k.innerHTML='<a href="https://wiki.openstreetmap.org/wiki/Key:'+
m+'" target="_blank"><tt>'+m+"</tt></a>";for(k=0;k<a.f[m].length;k++)g.innerHTML+="<span class='attrval'>"+a.f[m][k]+"</span><br>";b[m]=r}for(k=0;k<a.w.length;k++){g=a.w[k];r=b[g.s[0]];G(r,"err-"+Math.round(10*g.W));var A=F("div");g.h?A.innerHTML=g.a!=a.c?1<g.a?"Does not match <tt>"+g.g[0]+"</tt> in relation <a onmouseover='grHl( "+g.h+")' onmouseout='grUnHl( "+g.h+')\' target="_blank" href="//www.openstreetmap.org/relation/'+Math.abs(g.a)+'">'+Math.abs(g.a)+"</a>":"Does not match <tt>"+g.g[0]+"</tt> in relation <span onmouseover='grHl( "+
g.h+")' onmouseout='grUnHl( "+g.h+")'>"+Math.abs(g.a)+"</span>":"Does not match <tt>"+g.g[0]+"</tt> = '"+g.g[1]+"'":(q=0>g.a?"way":"node",A.innerHTML="Does not match <tt>"+g.g[0]+"</tt> in "+q+" <a onmouseover='stHl( "+g.I+")' onmouseout='stUnHl( "+g.I+')\' target="_blank" href="//www.openstreetmap.org/'+q+"/"+Math.abs(g.a)+'">'+Math.abs(g.a)+"</a>");G(A,"attr-err-info");r.childNodes[1].appendChild(A)}h.appendChild(n);1!=a.c&&h.appendChild(f);for(m in a.da)k=a.da[m],r=F("div"),q=0>k.c?"Way":"Node",
r.innerHTML=q+" <a onmouseover='stHl( "+k.id+")' onmouseout='stUnHl( "+k.id+")' target='_blank' href='//www.openstreetmap.org/"+q.toLowerCase()+"/"+Math.abs(k.c)+"'>"+Math.abs(k.c)+"</a>",k.f.name&&(r.innerHTML+=' (<b>"'+k.f.name+'"</b>)'),r.style.backgroundColor=k.e?"#f58d8d":k.O?"#b6b6e4":"#c0f7c0",1==a.c||k.oa!=a.id?n.appendChild(r):(f.appendChild(r),k.group!=a.id&&G(r,"del-stat"));n=F("ul");a.m.length&&(f=F("span"),G(f,"sugtit"),f.innerHTML="Suggestions",d.appendChild(f));d.appendChild(n);for(k=
0;k<a.m.length;k++)f=a.m[k],m=F("li"),6==f.type?m.innerHTML="Fix attribute <tt>"+f.s+"</tt>.":7==f.type?m.innerHTML="Consider adding a <tt><a target='_blank' href='https://wiki.openstreetmap.org/wiki/Key:name'>name</a></tt> attribute.":8==f.type&&(m.innerHTML="Attribute <tt>"+f.s+"</tt> seems to be a track number. Use <tt>ref</tt> for this and set <tt>"+f.s+"</tt> to the station name."),n.appendChild(m);h.appendChild(d);L.aa({opacity:.8}).ca(c).ba(h).Y(M).l("remove",function(){B=-1;V(a.id)})}
function W(a,c){J("g","/group?id="+a,function(a){T(a,c)})}function U(a){!v[a]||v[a].v({weight:6,color:"#eecc00"})}function V(a){!v[a]||v[a].v({weight:3,color:v[a].options.fillColor})}function Q(a){w[a]&&(15<M.b()?w[a].v({weight:5,color:"#eecc00"}):w[a].v({color:"#eecc00"}))}function R(a){w[a]&&(15<M.b()?w[a].v({weight:17<M.b()?1.5:1,color:"black"}):w[a].v({color:w[a].options.fillColor}))}var M=L.map("map",{sa:L.canvas(),ja:!1}).ta([47.9965,7.8469],13);M.ha(L.control.U({position:"bottomright",prefix:'&copy; <a href="http://ad.cs.uni-freiburg.de">University of Freiburg, Chair of Algorithms and Data Structures</a>'}));
M.l("popupopen",function(a){var c=M.ra(a.target.S.fa);c.y-=a.target.S.ea.clientHeight/2;M.qa(M.ya(c),{ia:!0});X()});L.xa("http://{s}.tile.stamen.com/toner-lite/{z}/{x}/{y}.png",{X:20,U:'&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',opacity:.8}).T(M);var Y=L.A().T(M);M.l("moveend",function(){Z()});M.l("click",function(){X()});
function Z(){11>M.b()?J("m","/heatmap?z="+M.b()+"&bbox="+[M.i().D().F,M.i().D().H,M.i().C().F,M.i().C().H].join(),function(a){Y.V();var c=22-M.b(),b=25-M.b();Y.o(L.M(a.ok,{max:500,K:{0:"#cbf7cb","0.5":"#78f378",1:"#29c329"},N:.65,blur:c,J:b}));Y.o(L.M(a.ua,{max:500,K:{0:"#7f7fbd","0.5":"#4444b3",1:"#0606c1"},N:.65,blur:c-3,J:Math.min(12,b-3)}));Y.o(L.M(a.la,{max:500,K:{0:"#f39191","0.5":"#ff5656",1:"#ff0000"},N:.75,blur:c-3,J:Math.min(10,b-3),X:15}))}):J("m","/map?z="+M.b()+"&bbox="+[M.i().D().F,
M.i().D().H,M.i().C().F,M.i().C().H].join(),function(a){Y.V();v={};w={};for(var c=[],b=0;b<a.R.length;b++)w[a.R[b].j]=c[c.push(K(a.R[b]))-1];for(var h=[],b=0;b<a.L.length;b++)v[a.L[b].j]=h[h.push(N(a.L[b]))-1];for(var n=[],b=0;b<a.m.length;b++)n.push(O(a.m[b]));13<M.b()&&Y.o(L.A(h).l("click",function(a){W(a.G.options.id,a.G.i().ma())}));Y.o(L.A(c).l("click",function(a){S(a.G.options.id)}));15<M.b()&&Y.o(L.A(n).l("click",function(a){S(a.G.options.id)}));U(B);Q(C)})}
function X(){if(void 0!=y){clearTimeout(void 0);y=void 0;var a=x;x=void 0;if(a){var c=a.className.split(" ");delete c[c.indexOf("selres")];a.className=c.join(" ").trim();a.stat&&R(a.stat.j);a.group&&V(a.group.j)}E("#searchinput").value="";E("#sres").className=""}}E("#del").onclick=function(){X()};Z();
